export const timeZoneAndCountry = {
    "Albania": "Europe/Tirane",
    "Andorra": "Europe/Andorra",
    "Austria": "Europe/Vienna",
    "Belarus": "Europe/Minsk",
    "Belgium": "Europe/Brussels",
    "Bosnia and Herzegovina": "Europe/Sarajevo",
    "Bulgaria": "Europe/Sofia",
    "Croatia": "Europe/Zagreb",
    "Cyprus": "Asia/Nicosia",
    "Czech Republic": "Europe/Prague",
    "Denmark": "Europe/Copenhagen",
    "Estonia": "Europe/Tallinn",
    "Finland": "Europe/Helsinki",
    "France": "Europe/Paris",
    "Georgia": "Asia/Tbilisi",
    "Germany": "Europe/Berlin",
    "Greece": "Europe/Athens",
    "Hungary": "Europe/Budapest",
    "Iceland": "Atlantic/Reykjavik",
    "Ireland": "Europe/Dublin",
    "Italy": "Europe/Rome",
    "Kosovo": "Europe/Belgrade",
    "Latvia": "Europe/Riga",
    "Liechtenstein": "Europe/Vaduz",
    "Lithuania": "Europe/Vilnius",
    "Luxembourg": "Europe/Luxembourg",
    "Malta": "Europe/Malta",
    "Moldova": "Europe/Chisinau",
    "Monaco": "Europe/Monaco",
    "Montenegro": "Europe/Belgrade",
    "Netherlands": "Europe/Amsterdam",
    "North Macedonia": "Europe/Skopje",
    "Norway": "Europe/Oslo",
    "Poland": "Europe/Warsaw",
    "Portugal": "Europe/Lisbon",
    "Romania": "Europe/Bucharest",
    "Russia": "Europe/Moscow",
    "San Marino": "Europe/San_Marino",
    "Serbia": "Europe/Belgrade",
    "Slovakia": "Europe/Bratislava",
    "Slovenia": "Europe/Ljubljana",
    "Spain": "Europe/Madrid",
    "Sweden": "Europe/Stockholm",
    "Switzerland": "Europe/Zurich",
    "Ukraine": "Europe/Kyiv",
    "United Kingdom": "Europe/London",
    "Vatican City": "Europe/Vatican",
    "Antigua and Barbuda": "America/Antigua",
    "Bahamas": "America/Nassau",
    "Barbados": "America/Barbados",
    "Belize": "America/Belize",
    "Canada": "America/Toronto",
    "Costa Rica": "America/Costa_Rica",
    "Cuba": "America/Havana",
    "Dominica": "America/Dominica",
    "Dominican Republic": "America/Santo_Domingo",
    "El Salvador": "America/El_Salvador",
    "Grenada": "America/Grenada",
    "Guatemala": "America/Guatemala",
    "Haiti": "America/Port-au-Prince",
    "Honduras": "America/Tegucigalpa",
    "Jamaica": "America/Jamaica",
    "Mexico": "America/Mexico_City",
    "Nicaragua": "America/Managua",
    "Panama": "America/Panama",
    "Saint Kitts and Nevis": "America/St_Johns",
    "Saint Lucia": "America/St_Lucia",
    "Saint Vincent and the Grenadines": "America/St_Vincent",
    "Trinidad and Tobago": "America/Port_of_Spain",
    "United States": "America/New_York"
};

export type Country = keyof typeof timeZoneAndCountry;